name: Deploy to Production

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none
        
    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Install NPM Dependencies
      run: |
        npm ci
        npm run build
        
    - name: Run Tests
      run: php artisan test
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        # Copy deployment script to server
        scp deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/home/admin-tt/
        
        # Copy .env file if it exists
        if [ -f .env ]; then
          scp .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/home/admin-tt/htdocs/www.technical-test.site/
        fi
        
        # Execute deployment script
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "chmod +x /home/admin-tt/deploy.sh && /home/admin-tt/deploy.sh"
        
    - name: Verify Deployment
      run: |
        # Wait for deployment to complete
        sleep 30
        
        # Check if the application is responding
        curl -f https://www.technical-test.site/api/documentation || exit 1
        
    - name: Notify on Success
      if: success()
      run: |
        echo "Deployment completed successfully!"
        echo "Application is available at: https://www.technical-test.site"
        echo "API Documentation is available at: https://www.technical-test.site/api/documentation"
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment failed!"
        echo "Please check the logs for more information." 